name: Publish package to the Sonatype Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3

      # This shouldn't be needed since we hooked this up to all requests, but since we're publishing let's make sure
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run check and sign artifacts
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build 
                     check
                        -PORG_GRADLE_PROJECT_signingKey=${SIGNING_KEY}
                        -PORG_GRADLE_PROJECT_signingPassword=${SIGNING_PASSWORD}
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - name: Publish package
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: publishMavenPublicationToOssrhRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}